# Generated by Django 4.0.4 on 2022-05-29 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_country_states_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='countries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
        migrations.AlterField(
            model_name='option',
            name='states',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.states'),
        ),
    ]
