# Generated by Django 4.0.4 on 2022-05-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_option_countries_alter_option_states'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
