# Generated by Django 4.0.4 on 2022-05-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='created_date',
        ),
    ]
