# Generated by Django 4.0.4 on 2022-05-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_option_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
