# Generated by Django 4.0.4 on 2022-06-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=125, null=True)),
                ('last_name', models.CharField(blank=True, max_length=125, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_id', models.CharField(max_length=125, null=True)),
            ],
        ),
    ]
