# Generated by Django 4.0.4 on 2022-06-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procfile',
            new_name='Profile',
        ),
    ]
